### ISSUE TITLE
Reduce DNS response time and index page loading

### ISSUE THREAD

**Issue by vshpelyk** [LyashenkoGS/analytics4github#12]
Go to ns server https://www.cloudflare.com/

**Comment by LyashenkoGS** [comment]
Current average response time from DNS is about 450ms. The whole index page loads in about 5.5s. Need to decrease it to 3.5.
* use Cloudflare nameserver
* use CDN providers for front-end libraries(bootstrap, JQuery)

**Comment by vshpelyk** [comment]
The current average ping is about 200 ms. 
![screenshot from 2017-03-11 14-55-02](https://cloud.githubusercontent.com/assets/17647781/23823418/c6366ef4-066a-11e7-9015-86d3e7ed56b7.png)

The estimate ping average ping after to  the cloudflare as an NF provider ping is about 40 ms. For tests was used a site that hosted on AWS EC2 and uses Cloudflare as an NS provider
<img width="455" alt="screen shot 2017-03-11 at 1 13 32 pm" src="https://cloud.githubusercontent.com/assets/12611051/23823546/b47f6a3e-065c-11e7-8084-4d430488a65f.png">

**Comment by LyashenkoGS** [comment]
After Cloudflare has been assigned  as an NS server, an average ping became 23ms
<img width="458" alt="screen shot 2017-03-11 at 2 33 40 pm" src="https://cloud.githubusercontent.com/assets/12611051/23824070/c78dd1f0-0667-11e7-9fb0-a74021a43ebb.png">

**Comment by LyashenkoGS** [comment]
<img width="698" alt="screen shot 2017-03-11 at 2 39 14 pm" src="https://cloud.githubusercontent.com/assets/12611051/23824115/bd512dda-0668-11e7-8eff-220472b8e1ae.png">

To improve response time some JavaScript libraries will be used from a CDN

**Comment by LyashenkoGS** [comment]
We can't use CDN for the bootstrap.min.css because we use a custom bootstrap. 
A topic with techniques to leverage a page loading speed http://webmasters.stackexchange.com/questions/52502/how-can-i-speed-up-the-download-time-of-a-bootstrap-themed-website

**Comment by vshpely** [comment]
I offer to try Leverage browser caching

**Comment by LyashenkoGS** [comment]
For now, latency is ok.
