### ISSUE TITLE
Display available requests number

### ISSUE THREAD

**Issue by LyashenkoGS** [LyashenkoGS/analytics4github#16]
GitHub provides 5 000 requests per hour for authorised users. In your case authorised user is the analytics4github production server.A number of left requests can be acquired from a header of response from GitHub API. See  [https://developer.github.com/v3/#rate-limiting](https://developer.github.com/v3/#rate-limiting). 

The goal is to display current rate limit on the application start and update after each analyse operation(unique stargazers, commits, etc.)
![requestnumbercounter mockup](https://cloud.githubusercontent.com/assets/12611051/23521611/99ec66c2-ff77-11e6-8cbe-ceb1ae9ea849.png)

**Comment by azozello** [comment]
Closed

**Comment by LyashenkoGS** [comment]
Where is the code review?

**Comment by azozello** [comment]
http://134.249.116.246:8081/analytics-github/review/AG-CR-4

**Comment by LyashenkoGS** [comment]
#27 final pull request has been accepted
