### ISSUE TITLE
Trigger automatic analysis on a tab click

### ISSUE THREAD

**Issue by nazar-khimin** [LyashenkoGS/analytics4github#19]
- [x] As  a user, 
I want to see already analysed new stars for the current month and week during the application home page load.
- [x] As  a user, 
I want to trigger the "analyse" button automatically, at click on tabs(stars, commits, unique contributors)

**Stars**
![image](https://cloud.githubusercontent.com/assets/16464652/23822780/78f30dae-065c-11e7-9045-db63452d106f.png)
**Unique contributors**
![image](https://cloud.githubusercontent.com/assets/16464652/23822787/9920807a-065c-11e7-8cde-0def4d91ce0d.png)

**Comment by nazar-khimin** [comment]
If we double-click, it will work.
If click, it won't work.
![out](https://cloud.githubusercontent.com/assets/16464652/23831278/c2485d2c-0726-11e7-8a90-3fb92d0f9e3d.gif)

**Comment by LyashenkoGS** [comment]
Code review http://134.249.116.246:8081/analytics-github/review/AG-CR-3

A pull request has been temporarily rejected. https://github.com/LyashenkoGS/analytics4github/pull/23

**Comment by LyashenkoGS** [comment]
Triggering analytics on single click has been implemented. Code review http://134.249.116.246:8081/analytics-github/review/AG-CR-3
