### ISSUE TITLE
Change period of analytics

### ISSUE THREAD

**Issue by iivanyshyn** [LyashenkoGS/analytics4github#2]
We cater analytics only for a current month and current week. Add a feature to change analytics period on UI.
MockUps(open via draw.io) :
https://drive.google.com/file/d/0Bx7QUcP3ps_TMDZiUFdocExQVnc/view?usp=sharing
Acceptence creteria
1. Display current month start - end
2. On click display next or previous month
3. Prohibit pick up custom days. Only change month

**Comment by LyashenkoGS** [comment]
Generic request JSON:
{
  "repositoryName": "mewo2/terrain",
  "startDate": "2015-03-01",
  "endDate": "2015-03-31"   
}

Generic response JSON:  //represents a frequency of some event per week 
[
  {
    "name": "Stars",
    "data": [
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ]
  }
]

All dates are  ISO-8601  year-month-day format
