### ISSUE TITLE
Wrong month commits frequency

### ISSUE THREAD

**Issue by LyashenkoGS** [LyashenkoGS/analytics4github#26]
On the pictures there is the same commits frequency, despite different months
<img width="1240" alt="screen shot 2017-03-18 at 12 45 02 pm" src="https://cloud.githubusercontent.com/assets/12611051/24072203/34debea4-0bdb-11e7-8b7c-a6a09357791f.png">
<img width="1214" alt="screen shot 2017-03-18 at 12 45 17 pm" src="https://cloud.githubusercontent.com/assets/12611051/24072204/34e10682-0bdb-11e7-8443-ba25554259aa.png">

But there are no commits at all during January.

https://api.github.com/repos/terryum/awesome-deep-learning-papers/commits?since=2017-01-01T00:00:00Z&until=2017-01-31T00:00:00Z - January

https://api.github.com/repos/terryum/awesome-deep-learning-papers/commits?since=2016-12-01T00:00:00Z&until=2016-12-31T00:00:00Z - December

**Comment by azozello** [comment]
There is no commits during January
