### ISSUE TITLE
Dockerise application

### ISSUE THREAD

**Issue by vshpelyk** [LyashenkoGS/analytics4github#3]
Dockerise application according to the tutorial https://spring.io/guides/gs/spring-boot-docker/
Research how to add token

**Comment by LyashenkoGS** [comment]
Need to write an instruction how to run the application via docker locally, push completed docker image to https://hub.docker.com/r/lyashenkogs/analytics4github/

**Comment by LyashenkoGS** [comment]
Added token.txt support during building a docker container #6 
token.txt is mandatory now to dockerize the application. According to [http://stackoverflow.com/questions/31528384/conditional-copy-add-in-dockerfile ](http://stackoverflow.com/questions/31528384/conditional-copy-add-in-dockerfile ) there is no conditional "ADD' instruction.

**Comment by LyashenkoGS** [comment]
Need to research ways to provide acces to a MongoDB from a container.

**Comment by vshpelyk** [comment]
https://docs.docker.com/engine/examples/mongodb/

**Comment by LyashenkoGS** [comment]
Update. For simplicity, I decided to run a MongoDB instance in a docker container and persist date via [a volume](https://docs.docker.com/engine/tutorials/dockervolumes/#locating-a-volume).
Need to write a script bash that:
- [x] builds and run a docker container with the application
- [x] builds and run MongoDB in a docker container 
- [x] connects the container with the application to the container with MongoDB

**Comment by LyashenkoGS** [comment]
In the current implementation, the application connects to a MongoDB via `localhost:27017 `. Need to create additional application-docker.properties which set MongoDB address to the `mongodb:27017` .

- [x] create application-docker.properties for using a dockerized MongoDb instance
- [x] update a Dockerfile to use the application-docker.properties  by default

**Comment by LyashenkoGS** [comment]
To run the application and a MongoDB docker containers execute the script `./start_all_In_Docker.sh 
` . It will build and run the application, MongoDB container, bind ports to the host, map a data volume from a MongoDB container to the host `/tmp/mongodb` directory.
http://134.249.116.246:8081/analytics-github/review/AG-CR-8 - code review
